export const baseInsertsSQL = `
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת סנדוויץ חומוס עם אוראו', 32, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אכילת שוקולד למריחה עם כפית', 29, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת אוכל משימורים', 25, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לפרק שקית תפוציפס 200 גרם לבד', 30, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת פסטה עגבניות עם חומוס', 27, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מקדונלדס', 29, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('ברגעי חולשה אוכלת חביתה שהכנתי במיקרו', 26, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכל קורנפלקס כריות עם מים חמים', 32, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שותה אלכוהול בכל ארוחת ערב', 34, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת ישר מהסיר גם אם הוא קר', 27, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מערבבת במקדונלדס את החמוץ מתוק עם הקטשופ', 26, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לאכול ג''ומי מסוכר... אמאלה!', 29, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוכל עוגיות בכל פעם שאני מתעורר בלילה', 29, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('להמשיך לאכול למרות שאני שבעה', 35, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לאכול גלידה, אבל לשבת על חצי קילו של בן אנד גריס ב12 בלילה', 27, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('במבה עם מילקי אמאלה', 28, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לא מחממת שאריות אוכל, הפסטה של אתמול ממש טעימה קרה, ואם ישר מהקופסה אז בכלל (חוסך כלים!)', 28, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שותה חלב מהקרטון', 31, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שותה זירו מהפה ישר מהמקרר', 27, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכל פיצה קרה', 33, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכל כל דבר עם קטשופ', 19, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת טונה עם גבינה לבנה ומפזרת שבבי בצל מעל', 26, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול טורטית', 29, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת חטיף לארוחת ערב', 22, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת בן אנד גריס ישר מהקופסה מול הטלוויזיה', 28, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכלת שוקולד בשורות', 38, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכל פיצה מעדנות ב12 בלילה אחרי משחק', 25, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לאכול פופקורן בבית', 26, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לאכול במיטה', 21, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת ריח של תפוז בידיים', 25, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שוקולד', 25, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שוקולד', 21, 'female', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לעשן ולאכול משהו טעים', 30, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לחפוף את השיער 3 פעמים אחרי מסיבה שעישנו לידי', 23, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב להריח את כפות הרגליים של הכלב שלי', 27, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מעשנת בסתר', 29, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('80 אחוז מזמן המקלחת עומדת מתחת למים זורמים', 26, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כוססת ציפורניים', 26, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('נשארת בפיג׳מה כל היום', 27, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מוציאה נזלת יבשה מהאף', 26, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לחטט באף', 26, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת להוריד גרביים בטיסה', 27, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('הולכת עם גרביים טרמיות מהצבא', 25, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אמבטיות של שלוש שעות', 21, 'female', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתקלח 5 פעמים ביום', 29, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לקסוס ציפורניים', 23, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לגלול בטוויטר שעות', 23, 'male', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('סטוקינג באינסגרם', 31, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('יכול להיות שעות ביום בטלפון וברשתות חברתיות', 32, 'male', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לראות מלא יוטיוב', 23, 'male', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לגלול ברשתות חברתיות באחת בלילה במקום לישון למרות שאני קמה בשבע בבוקר', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לשחק בטלפון', 55, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('נשארת במיטה בטלפון ערה שעה בבוקר', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לחפור בעמוד אינסטגרם של מישהי לראות איך היא נראתה פעם', 24, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה סרטוני asmr', 26, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה סרטונים של פיצוץ חצ׳קונים והוצאת שחורים', 26, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מצלמת את עצמי רק עם פילטר', 41, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('משחק קנדי קראש', 29, 'male', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה מלא סרטוני מתכונים כשאני רעבה', 35, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לצלם אוכל לפני שאני אוכלת', 22, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לראות סרטונים של אנשים נופלים', 30, 'male', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני צופה שעות בסרטונים של הצעות נישואין', 30, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('עוקבת אחרי אישה אקראית באינסטגרם שלא מכירה אותי ואני מכירה את כל החיים שלה', 26, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('סרטוני asmr', 24, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני עוקב אחרי מישהו שאני לא מסכים איתו רק כדי להגיב לו', 38, 'male', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('יותר מידי הרבה זמן בשורטס או אינסטגרם', 21, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מרפרש את אתר החדשות עד שיהיה עדכון חדש', 42, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת לקרוא תגובות של אנשים לכתבות', 34, 'female', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה תמונות וסרטונים גרפיים מזירת אירוע', 38, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('להתווכח עם אנשים בתגובות', 29, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני צופה בערוץ הכנסת ומחכה לריבים', 49, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('במלחמה אני ישנה עם החדשות ברקע', 28, 'female', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כשיש מצב בטחוני קשה אני רואה חדשות 24/7', 27, 'female', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כרסום יסודות הדמוקרטיה', 75, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('פוליטיקה', 23, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קוראת הודעות של הבן זוג בלי שהוא רואה', 31, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מנגב ידיים במגבת גוף של בת הזוג', 25, 'male', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוכל כשאני לבד בבית ומסתיר ריאיות', 33, 'male', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מחביאה לבעלי חפצים וצופה בו מחפש', 33, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתחילה שיחות בטינדר ונעלמת', 26, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כותב הודעות ארוכות לאנשים ואז מוחק', 26, 'male', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('בודקת מה הסטטוס האקסים שלי', 31, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפנטזת על הבן זוג של חברה שלי', 33, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מאזין לשיחות של אנשים זרים בציבור', 45, 'male', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שולחת את הכלב שיעיר את בעלי כשאני רוצה שיקום', 37, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני הולכת למחרת וקונה בכוונה כל דבר שבעלי אמר לי שאני לא יכולה לקנות', 38, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני עושה כאילו אני נרדמת על הספה כדי שהבן זוג יכסה אותי', 28, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני חוזרת לקרוא את כל ההודעות שלי עם האקס מההתחלה', 27, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קניות אונליין לפני השינה בלי שהבן זוג יראה', 27, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני רואה משחק של הקבוצה שאני שונא כדי לראות אותם מפסידים', 32, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לובש את אותם תחתונים בכל פעם שהקבוצה שלי משחקת', 34, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מקריין משחקים בפיפא', 18, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לובשת בגדי ספורט כדי שיחשבו שהתאמנתי למרות שלא', 28, 'female', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('הולך למשחקים של הפועל בתור אוהד מכבי כי יש כרטיס חינם', 29, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת לבכות ולהתאמן', 26, 'female', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('משאיר כביסה מקופלת על המיטה כמה ימים', 39, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('להשתמש בחד פעמי כדי לא לעשות כלים', 29, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני עדיין ישן עם הבובה שלי משהייתי ילד', 20, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהבת את פסח', 26, 'female', 'אורח חיים');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אני כל שבוע עושה מסאג׳', 31, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לעקוב אחרי שיירות נמלים', 33, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני ממלאה דלק רק כשהרכב מסמן לי', 46, 'female', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפעיל וויז גם כשאני יודע את הדרך', 31, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מוחצת נמלים בין האצבעות', 25, 'female', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כשאני עובדת מהבית בהפסקה שלי אני הולכת לישון', 27, 'female', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('פלאנר!!', 30, 'female', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לקלף תוויות מחיר', 26, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('משאירה בגדים חדשים שקניתי מחוץ לארון כמה ימים', 50, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה צמחים למרות שאני יודעת שימותו', 51, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מזמינה מלא מאליאקספרס', 27, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('גולל באסוס בלי מטרה', 25, 'male', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('ממלאה סלים ויוצאת מהאתר בלי להזמין', 27, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('ממששת את כל הבדים בחנות', 25, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('ריאליטי, כמה שיותר טראשי יותר טוב. באופן כללי תרבות פופ ברמה הכי נמוכה שיש, סלבס סוג ז׳ ומטה', 27, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צופה בתוכניות ריאליטי הכי טראש שקיימות- ערוץ tlc', 27, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צופה באנטומיה של גריי בפעם הרביעית', 30, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צפיה באף הגדול', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לצפות בבואו לאכול איתי', 46, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לראות סדרות על רוצחים סדרתיים', 35, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('עורך דפי ויקיפדיה', 46, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צופה בטלנובלות (אופרות סבון) קוריאניות', 36, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת לשמוע שירי יום הזיכרון לא ביום הזיכרון ולבכות', 28, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קוראת ספרי רומנטיקה', 49, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב משחקי מחשב אלימים', 21, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לראות האח הגדול', 29, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('ממציאה ריקודים לשירים שאני אוהבת בבית', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צופה בwwe', 30, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שומעת שירי פסטיגל', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה סרטי קומדיה רומנטית', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('BL', 23, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה גיא פינס', 23, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('שומעת שיר שאני אוהבת 15 פעם ברצף', 27, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רואה בובספוג', 29, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('תוכניות לנוער וילדים וראליטי', 27, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('רופול דראג רייס', 27, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('בשבת בבוקר אני עושה מרתון תום וג׳רי', 30, 'male', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('משחקת בסימס', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צורחת טיילור סוויפט באוטו', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהבת ריח של גשם', 52, 'female', 'מזג אוויר');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב ריח של זיעה', 56, 'male', 'מזג אוויר');
INSERT INTO confessions (confession, age, sex, category) VALUES ('להישרף בשמש ואז לקלף', 32, 'female', 'מזג אוויר');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהבת להירדם עם רעש של גשם', 20, 'female', 'מזג אוויר');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול גלידה באמצע החורף', 24, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לא מצאתי אף פעם סדרת טלוויזיה שאהבתי יותר מפעם אחת', 30, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מעדיף לשכב במיטה ולא לקום לעשות ספורט', 28, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה מלא בגדים ולא לובש אותם אף פעם', 22, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('צופה בחדשות רק כשהן סוערות במיוחד', 35, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתעצל לעדכן את הסמארטפון במשך חודשים', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לפעמים משקר שאני חולה כדי להישאר בבית', 31, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני תמיד מאחר לפגישות חברתיות כי מתעכב על הוואטסאפ', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לקום מוקדם ולרוץ, אבל עושה את זה רק פעם בחודש', 26, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתבאס כשמזג האוויר חם מדי ולא אפשר לצאת לטייל', 33, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול חומוס עם הרבה טחינה', 21, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לא ראיתי אף פעם סרט ישראלי שלם', 24, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('נרשמתי לחדר כושר אבל הלכתי פעמיים בלבד', 27, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה קפה בכל בוקר אבל שותה רק חצי ממנו', 34, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קורא חדשות רק מהכותרות הראשיות', 28, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מחזיק כמה חשבונות מדיה חברתית אבל לא מפרסם כלום', 22, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד ללכת לרופא', 30, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שומר טלפון של האקס/ית שלי, למרות שהפסדנו קשר', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מעדיף לישון מאוחר ולהתעורר מאוחר', 25, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שונא את החום בקיץ אבל לא אוהב חורף', 31, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול פיצוחים עם סרט בטלוויזיה', 23, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני תמיד מפספס הופעות של אמנים שאני אוהב', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני עושה יוגה רק כשיש לי מצב רוח טוב', 29, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מחזיק מלא קופסאות אוכל בבית ולא משתמש בהם', 28, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני עוקב אחרי חדשות רק בפייסבוק', 32, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד להעלות תמונות באינסטגרם כי לא מספיק מושלם', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מדבר לעצמי כשאני לבד בבית', 31, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד להתחייב ליחסים ארוכי טווח', 24, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לאכול ארוחת בוקר במיטה', 30, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כשיש סערה אני נשאר בבית ומרגיש בטוח', 33, 'female', 'מזג אוויר');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול שוקולד על הבוקר', 22, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('כל סרט קומדיה שאני רואה אני צוחק על אותן בדיחות', 25, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתחבא מאחורי הטלוויזיה כדי לא להתאמן', 28, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה דברים באינטרנט ולא מחזיר אותם אף פעם', 33, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קורא חדשות רק לפני השינה כדי לא להירדם', 30, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מעדכן סטטוס בפייסבוק פעם ב-3 שנים', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מפחד ללכת למרפאה אפילו כשכואב לי', 31, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מחזיק קשר עם חבר/ה מהתיכון למרות שלא מדברים', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני תמיד שוכח מטריה ונתפס בגשם', 24, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול כריכים עם מלא ירקות', 23, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא מבין למה כולם צופים בסדרות האלו', 27, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתעמל רק כדי לא לאכול פחות', 30, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוסף קופסאות קרטון מחנויות למרות שאין לי צורך', 28, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא מעדכן את החדשות כבר שבועות', 32, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('פוחדת להעלות תמונות כי חושבת שלא נראות טוב', 25, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני דוחה בדיקות רפואיות כי זה מלחיץ', 29, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מתקשר לחברים רק כשאני צריך משהו', 31, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לשבת בבית עם ספר ולא לצאת', 27, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא אוהב שמש חזק וקונה משקפי שמש גדולים', 30, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול פסטה עם הרבה גבינה', 24, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מתלהב מכל הצגות התיאטרון', 29, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני עושה ספורט רק בחורף', 26, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה נעליים רק בגלל שהן יפות, לא נוחות', 28, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני צופה בחדשות כדי להיות מעודכן, אבל לא מבין כלום', 33, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לגלוש בטלפון בזמן ארוחה', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד מרופאים ומעדיף לטפל בעצמי', 30, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני תמיד שוכח לחזור לחברים אחרי שיחה', 25, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מעדיף לישון מאוחר ולקום מאוחר', 29, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מתבאס כשיש גשם בחופש', 32, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול בורקס עם גבינה בלילה', 23, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לא הצלחתי לסיים אף ספר שקניתי', 28, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לעיתים קרובות מוותר על אימון כי אני עייף', 27, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה מלא מוצרי טיפוח שלא משתמש בהם', 26, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קורא חדשות רק בשביל לדעת על הפוליטיקה', 31, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד להעלות תמונות באינסטגרם כי חושב שזה לא מעניין', 24, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני נמנע מבדיקות רפואיות כי זה מלחיץ אותי', 29, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שומר על קשר עם חברים רק דרך וואטסאפ', 28, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לשתות קפה על המרפסת בבוקר', 30, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני תמיד לובש מעיל גם כשחם קצת', 27, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול פלאפל עם כל הרטבים', 22, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא סיימתי אף פעם סדרת טלוויזיה שהתחלתי', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מנסה להתאמן אבל תמיד מוצא תירוצים', 29, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה בגדים רק בגלל שהם במבצע, גם אם לא צריך', 25, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קורא חדשות רק כשיש משהו דרמטי', 33, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מעדיף לשלוח הודעות ולא לדבר בטלפון', 28, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני נמנע מלטפל בבריאות השיניים שלי', 30, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מתקשר לחברים רק כשאני צריך משהו', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב להסתובב בשכונה בשעות הערב', 27, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שונא חורף אבל מתגעגע לקיץ', 31, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול תפוח אדמה אפוי עם חמאה', 24, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מעדיף ספרים דיגיטליים על פני נייר', 28, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('לעיתים קרובות דוחה אימונים כי חסר לי מוטיבציה', 27, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה פריטים לבית שלא ממש צריך', 29, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני צופה בחדשות רק כשמשהו גדול קורה', 31, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני משתמש באפליקציות רבות אך מחק כמעט את כולן אחרי שבוע', 26, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד לבדוק לחץ דם או סוכר', 30, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שומר על קשר עם חברים בעיקר דרך רשתות חברתיות', 28, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לטייל בטבע ולפעמים לשכוח מהטלפון', 27, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני תמיד שונא גשם כי זה מקלקל לי את התוכניות', 33, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול נקניקיות עם חרדל', 22, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא מבין את האופנה העכשווית', 25, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מנסה להתאמן אבל תמיד מוצא תירוצים שלא לצאת', 28, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה חפצים רק כי הם נראים טוב על המדף', 30, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קורא חדשות רק כדי לדעת מה קורה בעולם', 32, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מבלה שעות בגלישה אבל לא מפרסם כלום', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני דוחה בדיקות רפואיות כי אני מפחד מהתוצאות', 31, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מתקשר לחברים רק כשאני רוצה לצאת', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לשתות תה בערב לפני השינה', 26, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא אוהב חום חזק, מעדיף מזג אוויר קריר', 34, 'female', 'מזג אוויר');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול סוכריות מנטוס בזמן נהיגה', 23, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מעדיף להאזין למוזיקה במקום לצפות בטלוויזיה', 28, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('מתאמץ לעשות ספורט רק כשיש חברים', 27, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה גאדג׳טים שאין לי באמת צורך בהם', 30, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קורא חדשות רק כשיש דרמה פוליטית', 32, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני משתמש בטלפון שלי כל הזמן, גם בלילה', 26, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מפחד לגשת לטיפולים רפואיים', 31, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מתקשר לחברים רק כשאני זקוק לעזרה', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לשתות מיץ תפוזים קר ביום חם', 27, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא אוהב לחוץ של חורף ומעדיף שמש', 33, 'female', 'מזג אוויר');

INSERT INTO confessions (confession, age, sex, category) VALUES ('אוהב לאכול חטיפים מלוחים מול הטלוויזיה', 24, 'male', 'אוכל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני לא מסיים אף פעם ספר שאני מתחיל', 26, 'female', 'תרבות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מוותר על אימונים כי לא מוצא זמן', 29, 'male', 'ספורט');
INSERT INTO confessions (confession, age, sex, category) VALUES ('קונה בגדים חדשים למרות שיש לי כבר מלא', 28, 'female', 'צרכנות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני קורא חדשות רק כשיש משהו מעניין במיוחד', 31, 'male', 'חדשות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני מעדיף לשלוח הודעות מאשר לדבר בטלפון', 27, 'female', 'דיגיטל');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני דוחה בדיקות רפואיות כי אני מפחד', 30, 'male', 'בריאות');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שומר על קשר עם חברים בעיקר דרך רשתות חברתיות', 29, 'female', 'יחסים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני אוהב לצאת לטייל בשעות הערב', 27, 'male', 'אורח חיים');
INSERT INTO confessions (confession, age, sex, category) VALUES ('אני שונא חום חזק ומעדיף מזג אוויר קריר', 32, 'female', 'מזג אוויר');

`